# Config file for air
# https://github.com/cosmtrek/air

[build]
  bin = "bin/main"
  cmd = "go build -o ./bin/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["*_test.go"]
  follow_symlink = true
  full_bin = "./main"
  log = "air.log"
  main = "."

[log]
  color = true
  time = true

[serve]
  grace = 2000
  root = "."